### ISSUE TITLE
"breaking:" tag is taking in consideration non master branches

### ISSUE THREAD

**Issue by paulopontesm** [codacy/git-version#11]
This results in a jump of 2 major versions when publishing something with a "breaking" commit.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3610528/51176007-bc5dfe80-18b3-11e9-9e69-0848a79c3463.png">

**Comment by andreaTP** [comment]
I think this is a duplicate of #9

**Comment by paulopontesm** [comment]
hmm.. strange. I got this this with the latest version.
I'll try to check why this happened later

**Comment by paulopontesm** [comment]
Seems to do the same on minors 

![image](https://user-images.githubusercontent.com/3610528/51190061-42407080-18d9-11e9-8d07-59f489b75578.png)
