### ISSUE TITLE
[CY-3691] May be i miss somehting

### ISSUE THREAD

**Issue by dajor** [codacy/git-version#46]
Looks so easy or may be i did not get it:

Try to follow your example. i have create a git-version file in my git repository and i see the version output but i can not build any version number. 

# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - xxxx

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
      
      - name: New Version
        run: cat $(pwd)/git-version
      
      - name: New Version2
        run: NEW_VERSION=$($(pwd)/git-version)
      
      - name: New Version3
        run: echo $NEW_VERSION

**Comment by josemiguelmelo** [comment]
Hi @dajor ,

To get the version created on Git Version step, you should add an id to the step and then you can get the version using `${{ steps.get-version.outputs.version }}`.

Check the following example:

```
      - name: Git Version
        id: get-version
        uses: codacy/git-version@2.2.0

      - name: New Version
        run: echo ${{ steps.get-version.outputs.version }}
```

**Comment by josemiguelmelo** [comment]
Hi!
I'm closing the issue. Feel free to re-open it if you need any more help on this 🙂
Thanks,

**Comment by faiqsayed** [comment]
Hi, 
I have used exactly the same code and my version is not getting an update-
could you please rectify my mistake?

**Comment by jellydn** [comment]
It works as expected on my starter, FYI. 

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/870029/180717594-36aaf5e7-cdd3-4078-9b73-640ea7376333.png">

https://github.com/jellydn/fastify-starter/runs/7494890397?check_suite_focus=true
